# Generated by Django 3.2 on 2023-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('pregnancies', models.PositiveIntegerField()),
                ('glucose', models.PositiveIntegerField()),
                ('blood_pressure', models.PositiveIntegerField()),
                ('skin_thickness', models.PositiveIntegerField()),
                ('bmi', models.FloatField()),
                ('diabetes_pedigree_function', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('label', models.BooleanField(blank=True, default=None, null=True)),
                ('is_predicted_by_model', models.BooleanField(default=False)),
                ('is_trained', models.BooleanField(default=False)),
            ],
        ),
    ]
