# Generated by Django 3.2 on 2023-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientobservation',
            name='insulin',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
